export const SERVICES = [
  {
    slug: "aircon-installations",
    title: "Aircon Installations",
    desc: "Professional installation of airconditioning systems for homes, offices and commercial spaces.",
    cta: "Get an Installation Quote →",
    wa: "installation",
    icon: "Wrench",
  },
  {
    slug: "aircon-sales",
    title: "Aircon Sales",
    desc: "Need a new aircon? Speak to Tiaan about finding the right solution for your space and requirements.",
    cta: "Ask Tiaan →",
    wa: "sales",
    icon: "ShoppingBag",
  },
  {
    slug: "aircon-repairs",
    title: "Aircon Repairs",
    desc: "Aircon not cooling, leaking or giving trouble? Let Tiaan diagnose the problem and recommend the right repair.",
    cta: "Book a Repair →",
    wa: "repair",
    icon: "Hammer",
  },
  {
    slug: "aircon-servicing",
    title: "Aircon Servicing",
    desc: "Keep your airconditioning system clean and performing properly with professional servicing and maintenance.",
    cta: "Book a Service →",
    wa: "service",
    icon: "Fan",
  },
  {
    slug: "car-aircon-regas",
    title: "Car Aircon Regas",
    desc: "Car aircon not cold anymore? Have the system inspected and professionally regassed where appropriate.",
    cta: "Book a Regas →",
    wa: "regas",
    icon: "Snowflake",
    highlight: true,
  },
  {
    slug: "car-aircon-repairs",
    title: "Car Aircon Repairs",
    desc: "Problems with your vehicle's airconditioning system? Tiaan provides fault finding, servicing and repairs.",
    cta: "Get Car Aircon Help →",
    wa: "car",
    icon: "Car",
  },
];